# steps:
# # Step 1 — Build Docker image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/burner-samkumar4/weather-fe-repo/weather-fe:latest', '.']

# # Step 2 — Push image to Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/burner-samkumar4/weather-fe-repo/weather-fe:latest']

# # Step 3 — Configure kubectl for GKE
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       gcloud container clusters get-credentials weather-cluster \
#       --zone us-central1-a \
#       --project burner-samkumar4

# # Step 4 — Apply Kubernetes manifest
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'weather-fe.yaml']

steps:
  # Step 1 — Build Docker image with cache optimization
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: 
      - 'build'
      - '--cache-from'
      - 'us-central1-docker.pkg.dev/burner-samkumar4/weather-fe-repo/weather-fe:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/burner-samkumar4/weather-fe-repo/weather-fe:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/burner-samkumar4/weather-fe-repo/weather-fe:$COMMIT_SHA'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'

  # Step 2 — Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push', 'us-central1-docker.pkg.dev/burner-samkumar4/weather-fe-repo/weather-fe:latest']

  # Step 3 — Configure kubectl for GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-credentials'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials weather-cluster \
        --zone us-central1-a \
        --project burner-samkumar4

  # Step 4 — Apply Kubernetes manifest with rollout status check
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy'
    args: ['apply', '-f', 'weather-fe.yaml']
    
  # Step 5 — Verify deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'verify-deployment'
    args: 
      - 'rollout'
      - 'status'
      - 'deployment/weather-fe'
      - '--timeout=300s'

# Add substitutions for dynamic values
substitutions:
  _COMMIT_SHA: $COMMIT_SHA
  _PROJECT_ID: burner-samkumar4

# Optimize build options
options:
  logging: GCS_ONLY
  logStreamingOption: 'STREAM_OFF'
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Artifacts to store in GCS
artifacts:
  objects:
    location: 'gs://weather-fe-staging/artifacts/'
    paths: 
      - '.next/'
      - 'package.json'