apiVersion: v1
kind: Pod
metadata:
  name: weather-fe
spec:
  containers:
    - name: weather-fe
      image: weather-fe:latest
      ports:
        - containerPort: 3000
      env:
        - name: NEXT_PUBLIC_API_BASE_URL
          value: "http://localhost:7000"   # BE ka URL
